version: '3.7'
services:
  rails:
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    ports:
      - '3000:3000'
    networks:
      - dealdrive
    stdin_open: true
    tty: true
    environment: 
      RAILS_ENV: 'production'
    volumes:
      - .:/root/src # add our local code to dockerfile
    working_dir: /root/src

networks: 
  dealdrive:
