version: '3.7'
services:
  db:
    image: 'mysql:8.0'
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Kankroli@e11
      - MYSQL_DATABASE=distributor_agency_platform_api_prod
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:
    build: ./
    ports:
      - '3000:3000'
    links:
      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container

volumes:
  db: # named volume